### PR TITLE
remove duplicate record - 3.4 main

### PR DESCRIPTION
**Pull request by ldelossa**
When parsing the secdb with the following yaml structure:

```
// Details define a package's name and security fixes for said package
type Details struct {
	Name string `yaml:"name"`
	// fixed package version string mapped to an array of CVE ids affecting the package
	Secfixes map[string][]string `yaml:"secfixes"`
}

// Package wraps the Details
type Package struct {
	Pkg Details `yaml:pkg`
}

// SecurityDB is the yaml security database structure
type SecurityDB struct {
	Distroversion string    `yaml:"distroversion"`
	Reponame      string    `yaml:"reponame"`
	Urlprefix     string    `yaml:"urlprefix"`
	Apkurl        string    `yaml:"apkurl"`
	Packages      []Package `yaml:"packages"`
}
```

a duplicate record in 3.4 main breaks the yaml parser. It is the only secdb which has this issue. I'm assuming in this PR this is in error.

### CODE REVIEW

**Comment by mor1** [comment]
I commented on the referenced issue -- I think the better solution would be to regenerate these auto-generated secdb files.

**Comment by ldelossa** [comment]
@mor1 thanks a lot. Sounds good.

**Comment by ncopa** [comment]
@mor1 I think we should also check for duplicates when generating the yaml.

**Comment by ncopa** [comment]
fixed with alpinelinux/aports@33c9b879e1ac2712ea308a9c9e642d83b54d690d

**Comment by ldelossa** [comment]
hello @mor1 and @ncopa I'm experiencing this issue once again with alpine 3.7. 

ticket re-opened: https://github.com/quay/claircore/issues/56

**Comment by mor1** [comment]
hi @ldelossa -- ok, i'll try to take a look (others may get there first).
[ as i'm no longer funded by Docker to work on Alpine, it might take me a few days to get to it though! ]
thanks!

**Comment by ldelossa** [comment]
@mor1 @ncopa just a heads up, we are currently using your webserver to pull the sec dbs: 

https://github.com/quay/claircore/commit/16f63d40f177ac71b71c164dab0ce79589df5c7c

Is there a better place of contact for this, since this repo seems to be deprecated ?

**Pull request closed without merging**
